Update mainnet forking guide
nomiclabs/hardhat pull request #1617
Opened 2021-06-29 06:11 UTC by paco0x

- [x] (If this PR includes a **documentation change**) This PR's branch was created from the `website` branch, and this PR uses the `website` branch as its base branch.
- [ ] (If this PR includes a **bug fix**) Relevant tests have been included.
- [ ] (If this PR includes a **new feature**) The change was previously discussed on an Issue or with someone from the team.
- [ ] I didn't do anything of this.

---

Add docs of newly added RPC methods

2021-06-29 13:09 UTC, fvictorio commented
Thanks for this @paco0x. Can you please rebase and point this to the `website` branch?

2021-06-29 17:09 UTC, paco0x commented
done @fvictorio

2021-06-30 13:20 UTC, fvictorio approved these changes
LGTM. @feuGeneA what do you think?

2021-06-30 15:32 UTC, feuGeneA requested changes
Thank you @paco0x!!!

2021-06-30 15:32 UTC, feuGeneA commented on docs/guides/mainnet-forking.md
> +Once you've got local instances of mainnet protocols, setting them in the specific state your tests need is likely the next step. Hardhat provides several RPC methods that let you modify anything abo
```suggestion
Once you've got local instances of mainnet protocols, setting them in the specific state your tests need is likely the next step. Hardhat Network provides several RPC methods to help you with this.
```

2021-06-30 15:32 UTC, feuGeneA commented on docs/guides/mainnet-forking.md
> +### Modify storage of contract
```suggestion
### Modifying contract storage
```

2021-06-30 15:32 UTC, feuGeneA commented on docs/guides/mainnet-forking.md
> +### Set bytecode of an address
```suggestion
### Setting bytecode of an address
```

2021-06-30 15:32 UTC, feuGeneA commented on docs/guides/mainnet-forking.md
> +### Set account balance
```suggestion
### Setting account balance
```

2021-06-30 15:32 UTC, feuGeneA commented on docs/guides/mainnet-forking.md
> +### Set account nonce
```suggestion
### Setting account nonce
```
Changing from imperative to present participle, to match other, existing headings.

2021-06-30 15:32 UTC, feuGeneA commented on docs/guides/mainnet-forking.md
> +This will set the first storage position inside that contract to 1.
```suggestion
This will set the contract's first storage position (at index `0x0`) to 1.
```

2021-06-30 15:40 UTC, paco0x commented
Updated. Thanks for your suggestions @feuGeneA.

2021-06-30 16:14 UTC, feuGeneA approved these changes

2021-06-30 17:41 UTC, merged