Fully explain the benefit of chai.use
nomiclabs/hardhat pull request #1820
Opened 2021-08-24 13:04 UTC by aspiers

Newbies won't immediately understand why `chai.use` is normally needed, therefore they also won't know why it's a benefit that `hardhat-waffle` takes care of this automatically.  So document it explicitly.

- [x] Because this PR includes a **documentation change**, its branch was created from the `website` branch, and this PR uses the `website` branch as its base branch.
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.

2021-08-24 14:43 UTC, feuGeneA requested changes
Thank you for this contribution.

2021-08-24 14:43 UTC, feuGeneA commented on packages/hardhat-waffle/README.md
> +Also, you don't need to [call `chai.use` in order to use Waffle's Solidity matchers](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html).
```suggestion
Also, you don't need to call `chai.use` in order to use [Waffle's Chai matchers](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html).
```

2021-08-25 11:13 UTC, aspiers commented
Suggestion now squashed into the commit.

2021-08-25 12:26 UTC, feuGeneA approved these changes

2021-08-25 12:26 UTC, merged